### ISSUE TITLE
不知道为什么您的这个脚本会在网页上插入广告，如果不是您的行为请检测代码！

### ISSUE THREAD

**Issue by LisonFan** [JixunMoe/cuwcl4c#10]

**Comment by LisonFan** [comment]
广告代码：<iframe scrolling="no" frameborder="0" width="300px" height="300px" src="http://115.29.78.189/iiad/iiad.html" style="position: fixed; right: 0px; bottom: 0px;"></iframe>

**Comment by jixunmoe** [comment]
请给出会插入广告的页面。

**Comment by LisonFan** [comment]
@JixunMoe http://115.29.78.189/iiad/iiad.html

**Comment by LisonFan** [comment]
@JixunMoe 一个 iframe  框架

**Comment by LisonFan** [comment]
@JixunMoe 不知道为什么iframe  框架代码贴不上来..

**Comment by jixunmoe** [comment]
不是广告源地址，而是产生这个广告的页面

**Comment by LisonFan** [comment]
@JixunMoe exp.qq.com

**Comment by jixunmoe** [comment]
脚本运行时的日志，并没有执行任何规则：

```
VM77:925 [CUWCL4C][日志] 脚本开始执行。
VM77:925 [CUWCL4C][日志] 域名: qq.com; 完整地址: http://exp.qq.com/; 请求参数: {}
VM77:925 [CUWCL4C][日志] 脚本版本 [ 3.0.423 ] , 如果发现脚本问题请提交到 [ https://greasyfork.org/forum/post/discussion?Discussion/ScriptID=2600 ] 谢谢。
VM77:925 [CUWCL4C][日志] onStart 准备阶段 :: 开始
VM77:925 [CUWCL4C][日志] onStart 准备阶段 :: 结束
VM77:925 [CUWCL4C][日志] onBody 阶段 :: 开始
VM77:925 [CUWCL4C][日志] onBody 阶段 :: 结束
```

建议咨询本地网络供应商，或检查您的浏览器脚本、扩展、插件、外部程序。

**Comment by LisonFan** [comment]
@JixunMoe 关闭您的脚本就没有这个广告了

**Comment by jixunmoe** [comment]
那再打开呢

**Comment by LisonFan** [comment]
@JixunMoe 打开就有，关了就没有

**Comment by jixunmoe** [comment]
把脚本删了然后重新安装看看？另外能否提供安装的时拦截到的网络请求 (怀疑脚本依赖项被污染?)

**Comment by jixunmoe** [comment]
另外… 是只有这个域名有广告弹出吗?

**Comment by jixunmoe** [comment]
临时解决方法: 加入下面规则到 ADB 或兼容 ADB 规则的扩展程序：

```
||115.29.78.189^
```

**Comment by LisonFan** [comment]
@JixunMoe 重新安装后没有了，这个广告已经被ABP拦截的，其他网页没有注意，只有exp.qq.com最明显

**Comment by LisonFan** [comment]
@JixunMoe 脚本全在 https://greasyfork.org/zh-CN 下载的，怎么会被污染...

**Comment by jixunmoe** [comment]
脚本的依赖项目有一些是来自没有 HTTPS 的服务器 (虽然也是公用的开放服务器)，但 ISP 做手脚并不难。

`115.29.78.189` 这个 IP 搜不到有用的信息 :<

**Comment by jixunmoe** [comment]
金山上的举报: http://bbs.duba.net/thread-23344111-1-1.html
