### ISSUE TITLE
腳本設置介面 無法使用

### ISSUE THREAD

**Issue by orsmile** [JixunMoe/cuwcl4c#12]
在最新版腳本上面 進入脚本配置界面 會顯示

检测不到脚本，请检查是否被禁用！

如果您已经启用了脚本，请按下 F5 刷新页面看看。

不知道舊版會不會 請作者測試一下了感謝

**Comment by orsmile** [comment]
#11 應該是這個commit 造成的 因為腳本配置介面是在https協議下面

**Comment by jixunmoe** [comment]
嗯 我改一下

**Comment by jixunmoe** [comment]
最新的 Commit 修正了，然后发现忘了写 issue..

https://github.com/JixunMoe/cuwcl4c/commit/b07797b57fb6d60efb34cb41249f4fd9c23376f5
