### ISSUE TITLE
網易雲音樂

### ISSUE THREAD

**Issue by orsmile** [JixunMoe/cuwcl4c#14]
目前海外又被擋住了
看起來改網址 方法已經被封阻
現在再丟出請求前 會先用這個post資料出去(做驗證?)
然後return JSON 內容為code:200
(個人猜應該是判斷是否為海外的關鍵)
http://music.163.com/weapi/log/web?csrf_token=
然後再來會連到音樂的位置
http://m10.music.126.net/20151204154051/79c94bd1055345484f1fd662644cfb85/ymusic/01de/9ee3/36ff/a0806a89260639314df60dd4899a5377.mp3 (歌單中第六首)

http://m10.music.126.net/20151204184146/80467b2028fd090409b0016a2b030639/ymusic/9c95/3294/63ac/2a51c385d389a0649ed190fdfb1dd062.mp3 (歌單第一首)

會顯示
Forbidden

You don't have permission to access /20151204154051/79c94bd1055345484f1fd662644cfb85/ymusic/01de/9ee3/36ff/a0806a89260639314df60dd4899a5377.mp3 on this server.
Apache/2.2.3 (CentOS) Server at m10.music.126.net Port 80

**Comment by jixunmoe** [comment]
音樂資訊頁面能否提供？

**Comment by orsmile** [comment]
http://music.163.com/#/playlist?id=134384364

**Comment by jixunmoe** [comment]
我帮你看看 感觉改了很多内容

**Comment by jixunmoe** [comment]
``` text
112.90.246.49 m10.music.126.net
```

黄易又在 DNS 做手脚，Hosts 添加这行暂时解决 :D

我去看看其他功能失效怎么修。

**Comment by jixunmoe** [comment]
MP3 的网址前面加上 `http://203.130.59.9/` 应该也能用，例如

``` text
http://m10.music.126.net/20151204190030/19ccab2d6f0c80071dd682449b51ea28/ymusic/9c95/3294/63ac/2a51c385d389a0649ed190fdfb1dd062.mp3?wshc_tag=0&wsts_tag=56616ccd&wsid_tag=90202d41&wsiphost=ipdbm
```

变成

```
http://203.130.59.9/m10.music.126.net/20151204190030/19ccab2d6f0c80071dd682449b51ea28/ymusic/9c95/3294/63ac/2a51c385d389a0649ed190fdfb1dd062.mp3?wshc_tag=0&wsts_tag=56616ccd&wsid_tag=90202d41&wsiphost=ipdbm
```

Hosts 好像有時候跳不過去.. 這個 ip 能用。

**Comment by orsmile** [comment]
想問下是什麼原理? 查了一下那IP似乎是51CDN的IP?

**Comment by jixunmoe** [comment]
黄易访问 m10 的域名之后自动跳到自己的 CDN 地址

然后就发现了这个规律..

**Comment by jixunmoe** [comment]
我发现这个方法对黄易其它音乐服务器也有用，例如 m1~7 服务器。

**Comment by jixunmoe** [comment]
https://github.com/JixunMoe/cuwcl4c/commit/673bc11e9928612ce407aaa6b2ff425e363c8abb

新增尝试性功能：修正黄易的播放器 :D

**Comment by jixunmoe** [comment]
如果还有问题，请重新打开这个 issue 或新开一个 :D
