### ISSUE TITLE
黄易云音乐第一个曲目播放错误

### ISSUE THREAD

**Issue by ccloli** [JixunMoe/cuwcl4c#15]
在播放列表不为空的情况下直接点击播放按钮，播放的曲目并不是当前显示的曲目，停用脚本后正常。
![3 2fy8 4 _ am0x9q el](https://cloud.githubusercontent.com/assets/8115912/11608011/60765112-9b98-11e5-8827-51dcac2441c4.png)

Google Chrome 47.0.2526.73 (正式版本) m （32 位）
Tampermonkey Beta v3.13.4923

**Comment by ccloli** [comment]
已测试在删除缓存（localStorage['track-queue-cache']）刷新后播放正常，但是当存在缓存后再次刷新播放会出问题。

**Comment by jixunmoe** [comment]
收到 会重新研究强行刷新首首歌曲播放的问题

**Comment by jixunmoe** [comment]
原因是因为我让修正播放器已经有曲库的时候自动刷新播放曲目的数据。。不然还是会被解析到 m10 的域名导致海外用户无法正常播放。

**Comment by jixunmoe** [comment]
https://github.com/JixunMoe/cuwcl4c/commit/d92f5110598f5780c9e4587e94d977b94d67c1b6#diff-2

修好了 有问题请重开 Issue :D

**Comment by ccloli** [comment]
嗯，没问题了，辛苦了 :octocat:

**Comment by jixunmoe** [comment]
没事 感谢报告 :D

**Comment by ccloli** [comment]
刚刚再次遇到了上述问题（不确定前几天有没有出现这种情况），大部分情况下还是会播放错误的曲目，删除 localStorage['track-queue-cache'] 后再次正常

**Comment by jixunmoe** [comment]
因为我发现只能这样才能强行切换.. 

待修复/查找更适合的解决方案

**Comment by ccloli** [comment]
我尝试将 `out/CUWCL4C.user.js` 最新版本（492）中第 1653 行的 

```
self.bNx(self.bOB(+1), "ui");
```

改成了前一个版本（486）的

```
self.bHO = self.bOB(+1);
```

后似乎就好了，你看看可以么？

**Comment by jixunmoe** [comment]
我等下试试看 :D

**Comment by jixunmoe** [comment]
暂时就先回滚。
