### ISSUE TITLE
网易云音乐 海外不能播放

### ISSUE THREAD

**Issue by orsmile** [JixunMoe/cuwcl4c#21]
网易云音乐 海外又不能播放了
CDN 好像都不能用
不知道有没有办法解决?

**Comment by jixunmoe** [comment]
前两天更新过 如果还是没用我也没解了

到时候问问懂网宿cdn的看看有没有什么方法绕过

**Comment by jixunmoe** [comment]
不对 这是昨天

**Comment by jixunmoe** [comment]
昨天的更新已经修好了问题，但是偶尔会播放失败；跳下一首即可。
