### ISSUE TITLE
網易雲音樂 Firefox不能正常播放

### ISSUE THREAD

**Issue by orsmile** [JixunMoe/cuwcl4c#23]
如標題
Chrome測試可以正常播放
Firefox不能播放

**Comment by jixunmoe** [comment]
开了海外用户模式没有？

另外，什么操作系统和浏览器版本？

最后我笔记本硬盘坏了，最迟周四才能修。

**Comment by jixunmoe** [comment]
另外尝试替换 #22 提到的脚本，能不能用？

**Comment by orsmile** [comment]
Win10X64 Firefox 44 油猴應該也是最新版本的
腳本我再試試

**Comment by r08ertliu** [comment]
May I know how to replace the script? From which line to which line? Thanks

**Comment by orsmile** [comment]
試了一下 好像可以work 不過有時候會卡住 需要換首才可以

**Comment by jixunmoe** [comment]
有些版权音乐 m10 解析不了。

解析失败时将尝试不同码率，如果全部失败则自动下一首。

**Comment by jixunmoe** [comment]
@robert0206liu try update to latest version. It should've fixed; however if it doesn't, please try open a new issue.

**Comment by jixunmoe** [comment]
如果有特殊需求，请查阅 [JixunMoe/proxy-163](https://github.com/JixunMoe/proxy-163)。

**Comment by orsmile** [comment]
Hi, 我之前用514版本加上 #22 Firefox 是可以听的 换到518就无法使用

**Comment by jixunmoe** [comment]
找到问题了.. 马上推送更新。
