### ISSUE TITLE
问两个网易云音乐的问题

### ISSUE THREAD

**Issue by heroboy** [JixunMoe/cuwcl4c#28]
现在播放收费和版权歌曲的方式是修改每首歌的属性，能修改掉服务器返回的用户的属性让它认为当前是高级别用户。这样能不能简化一点破解的方式呢？
有可能做个代理来破解网易云音乐的客户端播放器呢？

**Comment by jixunmoe** [comment]
1. 没仔细检查，反正能用所以我也没想太多。另外需要拦截请求歌曲的连接才可以实现高音质下载的解析。
2. 没记错的话，网络请求都上了 RSA(还是 AES?) 加密，可能记错。虽然可以注入脚本进去，但是我调不动。
