### ISSUE TITLE
请问这个谜一样的版本升级是怎么回事啊

### ISSUE THREAD

**Issue by Adiwon** [JixunMoe/cuwcl4c#31]
显示在 https://jixunmoe.github.io/cuwcl4c/config/  配置页面的信息

```
发现更新!
您当前的版本: 3.0.564，最新版为: 3.0.562。

您可以单击 此处 更新。
```

这个版本号是怎么回事？试了下去greasyfork升级脚本，也会跳出脚本降级警告的页面……
不过脚本功能倒是一切都正常的。

**Comment by jixunmoe** [comment]
应该是 GreasyFork 同步失败了，我去戳一戳强制更新看看。

**Comment by jixunmoe** [comment]
嗯修好了。

脚本配置界面直接读的 GreasyFork 数据，所以版本号有时候是会有一点偏差的。

**Comment by jixunmoe** [comment]
对了，如果是使用 GitHub 连接更新的话可以不理会这个更新提示。
