### ISSUE TITLE
依赖太多的第三方库，导致经常安装失败。

### ISSUE THREAD

**Issue by heroboy** [JixunMoe/cuwcl4c#33]
以前碰到好几次了，现在https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js 完全下载不下来。
我想，反正你的代码是需要编译打包的，顺便把require的内容下载并合并到源文件里好了。

**Comment by jixunmoe** [comment]
这个文件就一个地方用到... 加载失败会卡住脚本的安装吗？

**Comment by heroboy** [comment]
是的
以前也碰到过其他js文件下载不下来，导致安装不了的。

**Comment by heroboy** [comment]
另外，配置页面也因为用了cloudflare的cdn，导致打不开了。

**Comment by jixunmoe** [comment]
那 翻个墙吧 _(:3__
