### ISSUE TITLE
lepan依旧失效

### ISSUE THREAD

**Issue by liangxyz** [JixunMoe/cuwcl4c#4]
http://www.lepan.cc/file-268451.html
我打开这个网址，依旧提示找不到跳转地址，我用的3.0.394最新版，FIREFOX 35.01

**Comment by jixunmoe** [comment]
我蠢了… 看到跳转后就以为是能用了 orz

**Comment by liangxyz** [comment]
作者我爱死你了，十分感谢您的作品，谢谢！！！
